### ISSUE TITLE
Tidy Python package management

### ISSUE THREAD

**Issue by stuartalexwhitehead** [springload/wagtailblocks#3]
The package metadata in `setup.py` can do with a tidy up.

- [X] GitHub URL is incorrect
- [X] GitHub repository name (`wagtailblocks`) doesn’t match Python package name (`wagtailcommonblocks`)
- [x] uses BSD license

See https://github.com/springload/wagtaildraftail for best-practice example.

**Comment by loicteixeira** [comment]
I renamed the repository to `wagtailcommonblocks` so we are left with updating the license.
